language: node_js
node_js:
  - "12.13"
before_install:
  - npm install -g typescript
install:
  - npm install
before_deploy: "npm run build"
deploy:
  provider: npm
  email: "$EMAIL"
  api_key: "$NPM_KEY"
  on:
    branch: main